### ISSUE TITLE
Plugin doesn't load.

### ISSUE THREAD

**Issue by IncorrectFadixer** [Atherys/NPCs#1]
https://pastebin.com/h34f4gVi

**Comment by fingoltin** [comment]
I'll have this fixed soon; not sure how it hasn't come up.

**Comment by IncorrectFadixer** [comment]
Tell me when its done and tyvm

**Comment by NeumimTo** [comment]
You will be notified automatically by github once this issue is closed...

**Comment by fingoltin** [comment]
@IncorrectFadixer can you try the newly published version?

**Comment by IncorrectFadixer** [comment]
where do I find it?

**Comment by fingoltin** [comment]
[Here](https://github.com/Atherys-Horizons/NPCs/releases). This is where you got it the first time, yes?

**Comment by IncorrectFadixer** [comment]
https://pastebin.com/Pg7Qypdm

EDIT: Same issue
