### ISSUE TITLE
Glowcolor & 2nd skin layer

### ISSUE THREAD

**Issue by IncorrectFadixer** [Atherys/NPCs#2]
Issue -1 I can't change the glowcolor, it's always white.

Issue -2 Also I can't enable/disable the 2nd skin layer on the npc.

Suggestion -1 Add perm conditions, custom deny message when I don't have the perms to talk to the npc. (Extra)

Suggestion -2 Add an option to turn on/off second layer on skins

**Comment by fingoltin** [comment]
@IncorrectFadixer can you turn this into three separate issues please (glow colour, skin layer, deny message). Also, I don't know if or when I'll get to them.
